dubbo:
  protocol:
    port: -1
    name: "dubbo"
  registry:
    address: nacos://114.215.196.38:8848
  # 消费者 订阅
  cloud:
    # * 对所有的接口感兴趣
    # 指定服务感兴趣，多个服务名用","隔开
    subscribed-services: "alipay-producer-fa"