server:
  port: 8818
spring:
  application:
    name: "sentinel-user"
  cloud:
    nacos:
      discovery:
        server-addr: "10.3.133.159:8848,10.3.133.159:8849,10.3.133.159:8850"

    sentinel:
      transport:
        port: 8719
        dashboard: 47.111.6.167:8180
